-- AlterTable
ALTER TABLE "Task" ALTER COLUMN "freeSlack" SET DEFAULT -1,
ALTER COLUMN "totalSlack" SET DEFAULT -1,
ALTER COLUMN "es" SET DEFAULT -1,
ALTER COLUMN "ef" SET DEFAULT -1,
ALTER COLUMN "ls" SET DEFAULT -1,
ALTER COLUMN "lf" SET DEFAULT -1;
